publish:
  stage: build
  image:
    name: ghcr.io/astral-sh/uv:debian-slim
    entrypoint: [""]
  script:
    - uv tool run mkslides build --config-file src/mkslides_config.yml --site-dir public --strict src/slides.md
  pages: true
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - public
